### ISSUE TITLE
layout orientation selected by user be default even on reload

### ISSUE THREAD

**Issue by bethropolis** [karanBRAVO/Code-Editor#5]
# layout issue

example i like left oriented layout but on refresh it is back to center

![Screenshot 2023-02-25 16 07 28](https://user-images.githubusercontent.com/66518866/221358600-a04bc577-1fde-491b-b7ac-3fabccc91b0d.png)

i'm working on the save feature where users choice of layout is saved to local storage then checked on load and changed accordingly but if you have a better idea just inform me

**Comment by karanBRAVO** [comment]
done this by storing the orientation in local storage.
